# Generated by Django 6.0.7 on 2026-08-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
