# Generated by Django 6.0.7 on 2026-08-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0009_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
